version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: mix phoenix.server
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'puddu_dev'
